FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./
ARG VITE_WEB3FORMS_ACCESS_KEY
ENV VITE_WEB3FORMS_ACCESS_KEY=$VITE_WEB3FORMS_ACCESS_KEY
ARG VITE_GITHUB_URL
ENV VITE_GITHUB_URL=$VITE_GITHUB_URL
ARG VITE_LINKEDIN_URL
ENV VITE_LINKEDIN_URL=$VITE_LINKEDIN_URL
ARG VITE_PORTFOLIO_URL
ENV VITE_PORTFOLIO_URL=$VITE_PORTFOLIO_URL
ARG VITE_EMAIL
ENV VITE_EMAIL=$VITE_EMAIL
ARG VITE_PHONE
ENV VITE_PHONE=$VITE_PHONE
ARG VITE_LOCATION
ENV VITE_LOCATION=$VITE_LOCATION
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]